name: emetrix_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  dio: ^5.0.3
  shared_preferences: ^2.0.18
  vibration: ^1.7.6
  path_provider: ^2.0.11
  animate_do: ^3.0.2
  shimmer: ^2.0.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.4
  connectivity_plus: ^3.0.3
  image_picker: ^0.8.6
  flutter_rounded_date_picker: ^3.0.2
  flutter_datetime_picker: ^1.5.1
  logger: ^1.3.0
  page_transition: ^2.0.9

  flutter_map: ^3.1.0
  latlong2: ^0.8.1

  google_maps_flutter: ^2.2.5
  google_maps_flutter_platform_interface: ^2.0.4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Bold.ttf
        - asset: fonts/Raleway/Raleway-Light.ttf
        - asset: fonts/Raleway/Raleway-Medium.ttf
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic

  assets:
    - assets/
    - assets/images/
    - assets/images/
