name: emetrix_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  connectivity_plus: ^4.0.2
  dartdoc: ^6.3.0
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  geolocator: ^10.0.1
  google_maps_flutter: ^2.2.5
  hand_signature: ^3.0.1
  image_picker: ^1.0.4
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.2
  page_transition: ^2.0.9
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.18
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  vibration: ^1.7.6
  image_gallery_saver: ^2.0.3
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_blancoE.png"
  min_sdk_android: 21
  adaptive_icon_background: "#005C9D" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/logo_blancoE.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
    # - family: Montserrat
    #   fonts:
    #     - asset: fonts/Montserrat/Montserrat-Regular.ttf
    #     - asset: fonts/Montserrat/Montserrat-Bold.ttf
    #     - asset: fonts/Montserrat/Montserrat-Light.ttf
    #     - asset: fonts/Montserrat/Montserrat-Medium.ttf
    #     - asset: fonts/Montserrat/Montserrat-Italic.ttf
    #       style: italic
    # - family: Raleway
    #   fonts:
    #     - asset: fonts/Raleway/Raleway-Regular.ttf
    #     - asset: fonts/Raleway/Raleway-Bold.ttf
    #     - asset: fonts/Raleway/Raleway-Light.ttf
    #     - asset: fonts/Raleway/Raleway-Medium.ttf
    #     - asset: fonts/Raleway/Raleway-Italic.ttf
    #       style: italic
    # - family: Prompt
    #   fonts:
    #     - asset: fonts/Prompt/Prompt-Regular.ttf
    #     - asset: fonts/Prompt/Prompt-Bold.ttf
    #     - asset: fonts/Prompt/Prompt-Light.ttf
    #     - asset: fonts/Prompt/Prompt-Medium.ttf
    #     - asset: fonts/Prompt/Prompt-Italic.ttf
    #       style: italic

  assets:
    - assets/
    - assets/images/
    - assets/theme/
